### ISSUE TITLE
Use Webpack for bundling

### ISSUE THREAD

**Issue by m1n1** [hm-riscv/vscode-riscv-venus#49]
Our extension has many small sourcefiles which can be bad for extension. Therefore a bundler is recommended see [here](https://code.visualstudio.com/api/working-with-extensions/bundling-extension)

**Comment by haerrel** [comment]
see changes in linked pull request

this might cause problems when trying to debug the extension since the new entrypoint to the extension is now dist/extension.js

when developing, either
* change package.json `main` entry back to `out/extension.js`
or
* change the `watch` script in package.json to `webpack --mode development`

Would be interesting on how to incrementally compile changes with `webpack --mode development **--watch**`. For me that did not work, because vscode thought its building forever
