### ISSUE TITLE
Support: Any way to pass parameters?

### ISSUE THREAD

**Issue by richardlett** [hm-riscv/vscode-riscv-venus#54]
I'd like to turn on access between stack and heap, but can't seem to find a way to pass regular venus parameters - in this case
"-ahs, --AllowHSAccess"

**Comment by haerrel** [comment]
Thanks for filing this!

Could you describe where and how you usually pass those parameters?

**Comment by m1n1** [comment]
![image](https://user-images.githubusercontent.com/43846168/100005202-df6b6a80-2dc8-11eb-8980-e26aa50c1dde.png)

I think it would be good to implement all of those "default" settings found in the screenshots. In the first version this could be done in the launch.json

I also had a look on console commands, however these are mostly for navigating the virtual file system, which we dont use at the moment. The above settings are exposed in the Driver.kt but there is no sign of them being used as console arguments.

Like @haerrel can I ask what version of venus you are using/referring to?

**Comment by richardlett** [comment]
My apologies, I forgot Berkeley modified the version they gave us. I'm not sure how to get it, but I'm guessing 0.1.1, as that's the latest tag.

https://github.com/ThaumicMekanism/venus

I usually pass the arguments either there, or sometimes if I run venus from the command line with `java -jar venus.-jar`

**Comment by m1n1** [comment]
All the parameters can be found and set in the extension settings now, see the picture below. Max History, Text Start and sim args are omitted because we dont suport them yet.

Some of the settings might make more sense to put in the launch.json (Or make them overridable there). More User Feedback is needed and wanted here. For now they all stay in the extension settings though. Also because this is not one of our priorities now.

![image](https://user-images.githubusercontent.com/43846168/109810940-81052200-7c2a-11eb-8174-9383508e986e.png)
